# CLA Check Workflow
#
# require the NetFoundry Contributor License Agreement
#
# REQUIRED SECRETS:
# * CLA_APP_ID
# * CLA_APP_PRIVATE_KEY

name: "CLA Check"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  cla:
    uses: netfoundry/cla/.github/workflows/cla-workflow.yml@main
    secrets:
      CLA_APP_ID: ${{ secrets.CLA_APP_ID }}
      CLA_APP_PRIVATE_KEY: ${{ secrets.CLA_APP_PRIVATE_KEY }}
